### PR TITLE
Add option to auto-reset to current player

### PR DESCRIPTION
**Pull request by Phanx**
This is one of a four-part pull request (Bagnon, Bagnon_Config, Bagnon_VoidStorage, and Wildpants) that does the following:

1. Adds an option to automatically reset to the current player when closing and reopening any window.

2. Always resets the bank and void storage windows to the current player when clicking on a bank or void storage NPC.

See also:

- https://github.com/tullamods/Bagnon/pull/418
- https://github.com/Jaliborc/Bagnon_VoidStorage/pull/1
- https://github.com/tullamods/Wildpants/pull/3

### CODE REVIEW

**Comment by Phanx** [comment]
Was there some concern with this pull request, or did it just get overlooked among its 3 siblings?

**Comment by Jaliborc** [comment]
No, no, was just not able to review it yet. Thinking of having the auto reset enabled for everyone instead of a checkbox.

**Comment by Phanx** [comment]
Alright. If you decide to go that route let me know, I did the localization updates in a separate branch first after I noticed how out of date they were (ie. so out of date they didn't even work) and can make a pull request just for that if you want.

On a side note, you may want to consider using the CurseForge localization app. It won't help when you rename the keys (which was the main problem here) but it makes the rest of the work of updating translations easier, and makes it more likely people will contribute, since they don't need to know anything about Lua or Git. You can even use it if you don't use the CurseForge packager; I use [this Lua script](https://gist.github.com/Phanx/a113eeb21c9e6de4c425) (based on [Jlam's shell script](https://github.com/ultijlam/ovale/blob/master/utils/localization.sh) which may be preferrable if you're on Mac/Linux) to pull translations from CurseForge and write them to my addon files, even though I am now using the CurseForge packager, since I like having the translations in the source code.

**Comment by Jaliborc** [comment]
Ok, that would be cool. I'm gonna go with no option for now and see how users react. I think no one will have complaints about the behaviour.

P.S: cool script!

**Pull request closed without merging**
